## Dic.2010
## By D.Rossell
## Script for generating heatmaps of avg(flex_rmsd) obtained from Fam.vs.Fam structural superpositions in each HPK group
## This script used the .Rdat files generated by "heatmaps_flex-rmsd_families-in-groups.pl"
## 
##
## Usage:
## old: R CMD BATCH /home/malonso/phd/kinome/scripts/Rheatmaps.R
##
## R --vanilla < script.R
##

library(Heatplus)
library(gplots)
library(amap)

drawHeatmap <- function(filename) {
  ## Loading data file
  z <- read.table(filename,header=FALSE,sep='\t')
  ## Reading HPK families' names
  n <- unique(as.character(z[,1]))
  ## Defining a matrix of nrow=ncol (hpk families)
  zmat <- matrix(0,nrow=length(n),ncol=length(n))
  colnames(zmat) <- rownames(zmat) <- unique(as.character(z[,1])) #assign rownames, colnames
  
  ## Populating the matrix
  for (i in 1:nrow(z)) {
    # Populate only Diagonal Matrix
    zmat[z[i,1],z[i,2]] <- z[i,4]
    #  Populate complementary Diagonal Matrix
    zmat[z[i,2],z[i,1]] <- z[i,4]
  }
  
  #diag(zmat) <- 0 # Make the diagonal = 0
  #midpnt <- mean(range(zmat[zmat>0])) # Gets the midpoint value of the values range in the matrix. 
  #zmat[zmat==0] <- midpnt # Assigns midpoint value wherever there's a 0 in the matrix.
                          # By doing this we "hide" the unwanted values (those that I dont want to be shown in the plot) in the diagonal matrix.
  
  ## Setting colors for the heatmap
  col <- c(colorpanel(50, 'blue','cyan'),colorpanel(50, 'cyan','green'),colorpanel(50, 'green','yellow'),colorpanel(50, 'yellow','orange'),colorpanel(50, 'orange','red'))
  
  ## Clustering the matrix
  cl1 <- hcluster(x=zmat, method="spearman", link="average")
  cl2 <- hcluster(x=t(zmat), method="spearman", link="average")
  
  ##
  # R default values for mar=c(5.1,4.1,4.1,2.1)and oma=c(0,0,0,0) 
  ## Creating the heatmap
  ##heatmap_2((zmat), legend=2, col=col, scale='none',legfrac=15,Rowv=NA, Colv=NA) ## unclustered
  heatmap_2((zmat), legend=2, col=col, scale='none',par(mai=c(0.1,0.1,0.1,0.1)),legfrac=50, Rowv=as.dendrogram(cl1), Colv=as.dendrogram(cl2))  ## clustered
  
  ## Applying lables to the heatmap
  mtext('547 HPKD R3DS. Spearman. Avg',side=3,line=0.4)
  #mtext('Avg Rigid RMSD',side=2,line=0.3)
  #mtext('All Groups families',side=1,line=2.5)
  #mtext('All Groups families',side=4,line=0.5)
}

#fnames <- read.table('Rdat.list',header=FALSE)
#fnames <- as.character(fnames[,1])
#fnamesout <- sub('\\.Rdat','.dendT.ps',fnames)
#for (i in 1:length(fnames)) {
#  #pdf(fnamesout[i], family='Courier', pointsize=7)
#  postscript(fnamesout[i], family='Courier', pointsize=10)
#  drawHeatmap(fnames[i])
#  dev.off()
#}

#### 
fnames="/aloy/scratch/malonso/struct_alignments/daliLite/dali_data_547_pairwise_noAtyp.dat"
fnamesout <- sub('\\.dat','.ps',fnames)
#postscript(fnamesout, family='Courier', pointsize=3)
postscript(fnamesout, family='Courier', pointsize=3,  width = 20, height = 20, paper='special',title="541 HPKD R3DS (no Atyp). Spearman. Avg")
drawHeatmap(fnames)
dev.off()





